### ISSUE TITLE
블로그 홈페이지 다듬기

### ISSUE THREAD

**Issue by sihyun10** [sihyun10/sihyun10.github.io#3]
## 목적
> 현재 ```Chirpy``` 블로그 형식이기에 커스터마이징이 필요하다.

## 작업 내용
- [x] 블로그 타이틀 폰트 줄이기
- [x] 아래쪽에 트위터 아이콘 없애기 (사이드바 하단의 아이콘들 정리)
- [x] Footer 수정
- [x] favicon 변경하기
- [x] 구글 검색엔진에 노출될 수 있게 하기
- [x] 댓글 달 수 있도록 설정하기
- [x] 포스팅 작성하고, 잘 보이는지 확인하기
- [x] 404 에러 페이지 수정 (홈화면으로 돌아갈 수 있는 링크 남기기)

**Comment by sihyun10** [comment]
<img src="https://github.com/sihyun10/sihyun10.github.io/assets/92582664/8411be3e-0d05-496f-88a3-b386fdc1a7c3" width="700" height="200"/>    

문제를 발견했다.  
모바일로 내 블로그를 보게 되면 Chirpy 테마의 이미지가 보이게 된다. 모바일에서도 내 이미지가 보이게 바꾸고 싶다.

(해결방안)  
- 현재 ```assets\img\favicons```에 들어가보면 아래와 같다.  
![image](https://github.com/sihyun10/sihyun10.github.io/assets/92582664/090a50c0-da18-4df2-8e67-887223a4cdd3)

- 즉 내 이미지가 없기에 내 이미지가 안보였던 것이다. 이 사진들을 변경해주면 된다!

**Comment by sihyun10** [comment]
<img src="https://github.com/sihyun10/sihyun10.github.io/assets/92582664/37bd8224-49f2-4f61-b459-87c192e05372" width="700" height="200"/>  

이제 알맞게 잘 보인다!!

- 해결할 수 있었던 파비콘 생성해주는 사이트
https://realfavicongenerator.net/

사이트에서 파비콘을 생성한뒤, ```browserconfig.xml, site.webmanifest```파일은 삭제 후 ```assets\img\favicons```파일에 이미지를 덮어씌워주었다.

**Comment by sihyun10** [comment]
- 구글 검색엔진에 노출될 수 있게 하기

![image](https://github.com/sihyun10/sihyun10.github.io/assets/92582664/7c3833a9-7527-4ab9-9557-7e300074db15)

sitemap을 google에 등록해두었고, 등록을 해놈으로써  
 google에서 주기적으로 크롤링을 해준다고 한다.  

이제 google에서 색인을 완료하면 관련 검색어로 구글링했을때, 검색결과에서 내 글을 찾을수있다고 한다.

**Comment by sihyun10** [comment]
![image](https://github.com/sihyun10/sihyun10.github.io/assets/92582664/eba933f5-5245-4af8-9dad-317113d8f65a) 
 
![image](https://github.com/sihyun10/sihyun10.github.io/assets/92582664/3f41a795-c4f4-4362-aebf-28e8dd28b7ab)

<br>

네이버에서도 검색이 가능하도록 설정해주었다.

**Comment by yomce** [comment]
참고해서 발전된 블로그를 만들도록 하겠습니다 감사합니당 :)
